name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-typecheck:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Check uv lockfile
        run: uv lock --locked

      - name: Ruff Format Check
        run: uv run ruff format --check .

      - name: Ruff Linter
        run: uv run ruff check .

      - name: Mypy Strict Type Check
        run: uv run mypy src

  unit-tests:
    name: Unit Tests
    needs: [lint-and-typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run Unit Tests
        run: uv run pytest tests/unit

  integration-tests:
    name: Integration Tests
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Start Services
        run: docker compose -f docker-compose.dev.yml up -d --wait qdrant redis tei

      - name: Run Integration Tests
        run: uv run pytest tests/integration

      - name: Stop Services
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v
